-- SQL case statement are basically if-then-else logic inside a query.
-- For grouping and custom sorting


create database caseLecture;
use caseLecture;

create table employee (
	emp_id int primary key auto_increment,
    name varchar(23),
    department varchar(10),
    salary int,
    years_exp int
);

insert into employee(name,department,salary,years_exp)  values
('ALICE','IT',80000,6),
('BOB','HR',50000,3),
('CHARLIE','IT',65000,4),
('DIANA','FINANCE',90000,8),
('EVAN','HR',45000,2);





-- READ THE DATA
SELECT * FROM EMPLOYEE;


-- CLASSIFY EMPLOYEES BASED ON THEIR EXPERIENCE
SELECT
	NAME,
    DEPARTMENT,
    YEARS_EXP,
    -- EXPERIENCE CLASSIFICATION
    CASE
		WHEN YEARS_EXP >= 7 THEN 'SENIOR'
        WHEN YEARS_EXP >= 4 THEN 'MID LEVEL'
        ELSE 'JUNIOR'
	END AS EXPERIENCE_LEVEL,
    
    -- SALARY CATEGORY
    CASE 
		WHEN SALARY >=80000 THEN 'HIGH'
        WHEN SALARY > 60000 THEN 'MEDIUM'
        ELSE 'LOW'
	END AS SALARY_BAND,
    SALARY
FROM EMPLOYEE;





-- CASE IN WHERE CLAUSE
-- HR MUST BE >45000 AND REST DEPARTMENTS SHOULD BE >70000

SELECT
	NAME,
    DEPARTMENT,
    SALARY
FROM EMPLOYEE
WHERE 
	CASE 
		WHEN DEPARTMENT ='HR' THEN SALARY > 45000
		ELSE SALARY > 70000
    END;
    
    

-- CASE IN ORDER BY
-- IT FIRST , THEN HR , THEN FINANCE

SELECT 
	NAME,
    DEPARTMENT,
    SALARY
FROM EMPLOYEE
ORDER BY 
	CASE 
		WHEN DEPARTMENT ='IT' THEN 1
        WHEN DEPARTMENT ='HR' THEN 2
        ELSE 3
	END;



-- CONDITIONAL AGGREGATION

SELECT 
	DEPARTMENT ,
    COUNT(CASE WHEN SALARY >=60000 THEN 1 END) AS HIGH_EARNERS
FROM EMPLOYEE
GROUP BY DEPARTMENT;




-- VIEWS
-- A VIEW IN SQL IS BASICALLY A SAVED QUERY THAT LOOKS LIKE A TABLE BUT DOES NOT STORE DATA ITSELF;
SELECT
	NAME,
    DEPARTMENT,
    YEARS_EXP,
    -- EXPERIENCE CLASSIFICATION
    CASE
		WHEN YEARS_EXP >= 7 THEN 'SENIOR'
        WHEN YEARS_EXP >= 4 THEN 'MID LEVEL'
        ELSE 'JUNIOR'
	END AS EXPERIENCE_LEVEL,
    
    -- SALARY CATEGORY
    CASE 
		WHEN SALARY >=80000 THEN 'HIGH'
        WHEN SALARY > 60000 THEN 'MEDIUM'
        ELSE 'LOW'
	END AS SALARY_BAND,
    SALARY
FROM EMPLOYEE;



CREATE VIEW EMPLOYEE_DATA AS (
	SELECT
		NAME,
		DEPARTMENT,
		YEARS_EXP,
		-- EXPERIENCE CLASSIFICATION
		CASE
			WHEN YEARS_EXP >= 7 THEN 'SENIOR'
			WHEN YEARS_EXP >= 4 THEN 'MID LEVEL'
			ELSE 'JUNIOR'
		END AS EXPERIENCE_LEVEL,
		
		-- SALARY CATEGORY
		CASE 
			WHEN SALARY >=80000 THEN 'HIGH'
			WHEN SALARY > 60000 THEN 'MEDIUM'
			ELSE 'LOW'
		END AS SALARY_BAND,
		SALARY
	FROM EMPLOYEE

);

SELECT * FROM EMPLOYEE_DATA;

INSERT INTO EMPLOYEE(NAME,DEPARTMENT,SALARY,YEARS_EXP) VALUES('ARIK','SALE',60000,4);


-- WHY VIEWS ARE USEFULL

-- SIMPLIFY COMPLEX QUERIES
-- IMPROVE SECURITY(COLUMN-LEVEL ACCESS)
-- REUSABLE LOGIC
-- VIEWS - VIRTUAL TABLE
-- STORES QUERY , NOT DATA
-- ALWAYS REFLECT LATEST DATA
-- CAN USE , JOIN, CASE, WHERE ,GROUP BY



-- USER DEFINED FUNCTIONS

-- FUNCTION FOR SALARY CLASSIFICATION
DELIMITER $$

CREATE FUNCTION SALARY_CATEGORY(SAL INT)
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
	DECLARE CATEGORY VARCHAR(20);
    IF SAL>=80000 THEN
		SET CATEGORY = 'HIGH';
	ELSEIF SAL >= 60000 THEN
		SET CATEGORY ='MEDIUM';
	ELSE
		SET CATEGORY = 'LOW';
	END IF;
    
    RETURN CATEGORY;
END$$

DELIMITER $$;



SELECT 
	*,
    SALARY_CATEGORY(SALARY) AS SALARY_LEVEL
FROM EMPLOYEE;


-- CREATE FUNCTION FOR EXPERIENCE



