-- CONSTRAINTS ARE RULES APPLIED TO TABLE COLUMNS TO MAINTAIN DATA INTEGRITY,ACCUARCY, AND RELIABILITY IN DATABASE.

-- NOT NULL (IT ENSURES THAT YOU ARE NOT INSERTING THE NULL VALUES)
-- UNIQUE (YOU ARE INSERTING THE UNIQUE VAULES, IT WILL ALLOW NULL SINGLE TIME)
-- PRIMARY KEY (COMBINATION , NOT NULL + UNIQUE)
-- FOREIGN KEY 
-- CHECK (VALIDATES THE VALUE)
-- DEFAULT (IT SETS DEFAULT)
-- AUTO INCREMENT (AUTOMATICALLY GENERATE THE NUMBER)


-- NOT NULL CONSTRAINTS
CREATE TABLE STUDENTS(
	STUDENT_ID INT NOT NULL,
    NAME VARCHAR(30),
    AGE int
    );
DROP TABLE STUDENTS;
INSERT INTO STUDENTS(NAME,AGE) VALUES("ROHAN",20);


-- UNIQUE CONSTRAINT

CREATE TABLE STUDENTS(
	STUDENT_ID INT,
    USER_NAME VARCHAR(30) UNIQUE,
    AGE int
);

INSERT INTO STUDENTS(USER_NAME,AGE) VALUES("KRISH",34),("SOHIT",32);
DROP TABLE STUDENTS;

ALTER TABLE STUDENTS
DROP INDEX USER_NAME;

-- COMPOSITE PRIMARY KEY
CREATE TABLE STUDENTS(
	STUDENT_ID INT,
    COURSE_ID INT,
    PRIMARY KEY(STUDENT_ID,COURSE_ID) -- COMPOSITE PRIAMRY KEY
);

SELECT * FROM STUDENTS;

-- CHECK CONSTRAINT
CREATE TABLE STUDENTS(
	STUDENT_ID INT,
    AGE INT,
    CHECK(AGE<=30) -- IT'LL NOT ALLOW TO INSERT THE AGE >30
);

INSERT INTO STUDENTS VALUES (1,23);
INSERT INTO STUDENTS VALUES (2,31);


-- DEFAULT CONSTRAINT
CREATE TABLE STUDENTS (
	ID INT,
    LOGIN_TIME timestamp DEFAULT current_timestamp
);

INSERT INTO STUDENTS(ID) VALUES(1);

SELECT * FROM STUDENTS;
INSERT INTO STUDENTS(ID,LOGIN_TIME) VALUES(2,"2026-01-12 10:23:04");

DROP TABLE STUDENTS;
-- AUTO INCREMENT
CREATE TABLE STUDENTS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20)
);

INSERT INTO STUDENTS(NAME) VALUES("ROHIT"),("KRISHNA");
INSERT INTO STUDENTS(NAME) VALUES("NEHA");

SELECT * FROM STUDENTS;
DROP TABLE STUDENTS;