-- PROBLEM WITH SUBQUERIES IS BE CAN NOT REUSE IT
-- SUBQUERY WORKS BOTTOM TO TOP

-- CTE (Common Table expression)
-- CTE IS TEMPORARY TABLE, WE WILL ASSIGN THE NAME FOR IT
-- WE CAN REUSE IT AGAIN AS MUCH AS WE WANT
-- CTE CAN BE USED WITHIN THE SAME QUERY
-- DEBUGGING IS EASY
-- RECURSIVE QUERY
-- PERFORMANCE IS SAME AS SUBQUERY


CREATE DATABASE CTELECTURE;
USE CTELECTURE;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME  VARCHAR(20),
    DEPT_ID INT,
    SALARY INT);
    
CREATE TABLE DEPARTMENTS(
	DEPT_ID INT,
    DEPT_NAME VARCHAR(20)
);


INSERT INTO EMPLOYEES(NAME,DEPT_ID,SALARY) VALUES
("ALICE",10,60000),
("BOB",20,45000),
("CAROL",10,75000),
("DAVE",30,50000);

INSERT INTO DEPARTMENTS VALUES
(10,"HR"),
(20,"IT"),
(30,"FINANCE");

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- SELECTE THE DETAIL OF EMPLOYEES THOSE ARE IN HR DEPARMENT.
SELECT
	*
FROM EMPLOYEES 
WHERE DEPT_ID = 
	(SELECT 
		DEPT_ID
	FROM DEPARTMENTS
    WHERE DEPT_NAME = "HR");
    
-- SIMPLE CTE
WITH HREMPLOYEES AS (
	SELECT 
		DEPT_ID
	FROM DEPARTMENTS
    WHERE DEPT_NAME='HR'
)
-- MAIN QUERY
SELECT
	*
FROM HREMPLOYEES;
    
-- CTE WITH JOIN
WITH HREMPLOYEES AS (
	SELECT 
		DEPT_ID
	FROM DEPARTMENTS
    WHERE DEPT_NAME='HR'
)
-- MAIN QUERY
SELECT
	*
FROM EMPLOYEES E
JOIN HREMPLOYEES HE
ON E.DEPT_ID = HE.DEPT_ID;


-- MULTIPLE CTE 
WITH HIGHSALARY AS (
	SELECT 
		EMP_ID,
		NAME,
		DEPT_ID,
        SALARY
    FROM EMPLOYEES
    WHERE SALARY >= 50000
),
DEPT_INFO AS (
	SELECT
		DEPT_ID,
        DEPT_NAME
	FROM DEPARTMENTS
)

-- 
SELECT 
	H.NAME,
    D.DEPT_NAME,
    H.SALARY
FROM HIGHSALARY H 
JOIN DEPT_INFO D 
ON H.DEPT_ID = D.DEPT_ID;


-- CTE WITH AGGREGATION
-- AVERAGE SALARY PER DEPARTMENT
WITH AVGSALARY AS (
	SELECT
		DEPT_ID,
        AVG(SALARY) AS AVG_SALARY
	FROM EMPLOYEES
    GROUP BY DEPT_ID
)
SELECT
	D.DEPT_NAME,
    A.AVG_SALARY
FROM AVGSALARY A 
JOIN DEPARTMENTS D 
ON D.DEPT_ID = A.DEPT_ID;


-- RECURSIVE CTE

CREATE TABLE EMP(
	EMP_ID INT,
    NAME VARCHAR(20),
    MANAGER_ID int 
);
INSERT INTO EMP VALUES
(1,"ROHAN",NULL),
(2,"ALICE",1),
(3,"JAKE",1),
(4,"SOHIT",2),
(5,"KRISH",2),
(6,"LENA",3),
(7,"PAUL",4);

SELECT * FROM EMP;

WITH RECURSIVE EMPLOYEEHIERARCHY AS(
	SELECT
		EMP_ID,
        NAME AS EMPLOYEE_NAME,
        MANAGER_ID,
        1 AS LEVEL
	FROM 
		EMP
	WHERE MANAGER_ID IS NULL
    UNION ALL
    SELECT 
		E.EMP_ID,
        E.NAME,
        E.MANAGER_ID,
        EH.LEVEL+1
	FROM EMP E 
    JOIN EMPLOYEEHIERARCHY EH 
		ON E.MANAGER_ID = EH.EMP_ID
)
SELECT * FROM EMPLOYEEHIERARCHY;



WITH EMP_CTE AS (
	SELECT 
		EMP_ID,
        NAME,
        MANAGER_ID
	FROM EMP
)
SELECT 
	E.NAME AS EMPLOYEE_NAME,
    M.NAME AS MANAGER_NAME
FROM EMP_CTE E
LEFT JOIN EMP_CTE M
	ON E.MANAGER_ID = M.EMP_ID;
    


