use sat_sun10_am;


CREATE TABLE ORDERS(
	order_id INT primary key,
    payment_method varchar(20),
    amount_received FLOAT,
    product_id INT
);

INSERT INTO ORDERS VALUES
(101,"CASH",700,1),
(102,"ONLINE",360,2),
(103,"CARD",500,2),
(104,"CASH",780,3);


-- READ THE DATA 
SELECT 
	* 
FROM ORDERS;
CREATE TABLE products(
	product_id INT primary key,
    product_name VARCHAR(30),
    price float    
);


INSERT INTO PRODUCTS VALUES(1,"KEYBOARD",500),(2,"GPU",700);
INSERT INTO PRODUCTS VALUES(4,"MONITOR",650);
SELECT
	*
FROM PRODUCTS;


-- INNER JOIN,LEFT JOIN, RIGHT JOIN, FULL JOIN, CROSS JOIN, SELF JOIN
-- INNER JOIN , WILL REFLECT THE RECORDS IF PRODUCT_ID OF BOTH THE TABLES ARE MATCHING .
SELECT 
	O.ORDER_ID,
    O.AMOUNT_RECEIVED,
    P.PRODUCT_NAME,
    P.PRICE
FROM ORDERS O
INNER JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID;

-- LEFT JOIN, IT WILL REFLECT ALL THE RECORDS FROM THE LEFT TABLE AND COMMON RECORDS OF RIGHT TABLE.

SELECT 
	O.ORDER_ID,
    O.AMOUNT_RECEIVED,
    P.PRODUCT_NAME,
    P.PRICE
FROM ORDERS O
LEFT JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID;


-- RIGHT JOIN , IT WILL REFLECT ALL THE RECORDS FROM THE RIGHT TABLE AND COMMMON RECORDS OF LEFT TABLE. 
SELECT 
	O.ORDER_ID,
    O.AMOUNT_RECEIVED,
    P.PRODUCT_NAME,
    P.PRICE
FROM ORDERS O
RIGHT JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID;


-- FULL JOIN , COMBINATION OF LEFT AND RIGHT
SELECT 
	O.ORDER_ID,
    O.AMOUNT_RECEIVED,
    P.PRODUCT_NAME,
    P.PRICE
FROM ORDERS O
LEFT JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID

UNION

SELECT 
	O.ORDER_ID,
    O.AMOUNT_RECEIVED,
    P.PRODUCT_NAME,
    P.PRICE
FROM ORDERS O
RIGHT JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID;

-- CROSS JOIN , IT'S A PRODUCT OF RECORDS

SELECT 
	*
FROM ORDERS O
CROSS JOIN PRODUCTS P;


CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    MANAGER_ID INT
);
INSERT INTO EMPLOYEES VALUES
(1,"SOHIT",NULL),
(2,"ROHAN",1),
(3,"AMIT",1),
(4,"KRISHNA",2),
(5,"NEHA",2),
(6,"KASHISH",3);

SELECT * FROM EMPLOYEES;


-- SELF JOIN, 
SELECT
	E.EMP_NAME AS EMPLOYEE,
    M.EMP_NAME AS MANAGER
FROM EMPLOYEES E 
LEFT JOIN EMPLOYEES M 
ON E.MANAGER_ID = M.EMP_ID;