CREATE DATABASE KEYSCONCEPTS;
USE KEYSCONCEPTS;

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(30),
    PRODUCT_PRICE float
);

CREATE TABLE CUSTOMERS(
	CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(30),
    CITY  VARCHAR(20)
);

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    QUANTITY INT,
    PRODUCT_ID INT,
    CUST_ID INT,
    FOREIGN KEY(PRODUCT_ID) references PRODUCTS(PRODUCT_ID),
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


-- INSERT INTO ORDERS
INSERT INTO ORDERS VALUES
(1,3,101,201),
(2,2,101,202),
(3,5,102,202);

INSERT INTO ORDERS VALUES(4,6,103,203);

-- INSERT INTO CUSTOMERS
INSERT INTO CUSTOMERS VALUES
(201,"ROHIT","DELHI"),
(202,"SNEHA","DELHI")
;

INSERT INTO CUSTOMERS VALUES
(203,"DEV","MUMBAI");

SELECT * FROM CUSTOMERS;
-- INSERT INTO PRODUCTS
INSERT INTO PRODUCTS VALUES
(101,"MONITOR",3000),
(102,"RAM",5500),
(103,"SSD",6280);
SELECT * FROM PRODUCTS;



-- READ ORDERS DATA
SELECT * FROM ORDERS;


-- HOW TO GET SALE AMOUNT
SELECT 
    O.ORDER_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_PRICE,
    O.QUANTITY,
    C.CITY,
    P.PRODUCT_PRICE * O.QUANTITY AS SALE
FROM
    ORDERS O
        INNER JOIN
    PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
        INNER JOIN
    CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID;



-- GROUP TABLE BY CITY

SELECT 
    C.CITY, -- CUSTOMER
    SUM(P.PRODUCT_PRICE * O.QUANTITY) AS REVENUE
FROM ORDERS O
INNER JOIN PRODUCTS P 
ON O.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN CUSTOMERS C 
ON O.CUST_ID = C.CUSTOMER_ID
GROUP BY C.CITY;








