-- Subquery
-- query inside query
-- subquery works bottom to top

-- Types of subqueries
-- 01. Single row subquery
-- 02. Multiple row subquery
-- 03. Multiple columns subquery
-- 04. correlated subquery
-- 05. subquery with select
-- 06. subquery with from
-- 07. subquery with exists/not exists

create database subqueryClass;
use subqueryClass;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    DEPARTMENT VARCHAR(20),
    SALARY INT,
    MANAGER_ID int
);



INSERT INTO EMPLOYEES VALUES
(1,'AMIT','IT',60000,3),
(2,'NEHA','HR',45000,3),
(3,'ROHIT','IT',80000,NULL),
(4,'PRIYA','FINANCE',70000,5),
(5,'ANKIT','FINANCE',90000,NULL),
(6,'SNEHA','IT',50000,3);

-- READ THE DATA
SELECT * FROM EMPLOYEES;

-- 01 SINGLE SUBQUERY
-- SHOW EMPLOYEE WITH HIGHEST SALARY
SELECT	
	* 
FROM EMPLOYEES 
ORDER BY SALARY DESC 
LIMIT 1;
-- USING SUBQUERY
SELECT
	*
FROM EMPLOYEES
WHERE SALARY =
	(SELECT 
		MAX(SALARY) 
	FROM EMPLOYEES);

-- EMLOYEES EARNING MORE THAN AVERAGE SALARY
SELECT * FROM EMPLOYEES WHERE SALARY > 
(SELECT AVG(SALARY) FROM EMPLOYEES);


-- 02 MULTIPLE ROWS SUBQUERY

-- I WANT TO SELECT EMPLOYEES FROM DEPARTMENTS THAT HAVE MANAGERS
SELECT EMP_NAME FROM EMPLOYEES WHERE DEPARTMENT IN
(SELECT DISTINCT
	DEPARTMENT
FROM EMPLOYEES 
WHERE MANAGER_ID IS NOT NULL);



-- EMPLOYEES EARNING MORE THAN IT EMPLOYEE
SELECT
	EMP_NAME,
	SALARY
FROM EMPLOYEES
WHERE SALARY> ANY
	(SELECT
	SALARY
	FROM EMPLOYEES 
	WHERE DEPARTMENT = 'IT')
AND DEPARTMENT !='IT';



-- EMPLOYEES EARNING MORE THAN ALL IT EMPLOYEES

    
SELECT
	EMP_NAME,
	SALARY,
    DEPARTMENT
FROM EMPLOYEES
WHERE SALARY> ALL
	(SELECT
	SALARY
	FROM EMPLOYEES 
	WHERE DEPARTMENT = 'IT')
AND DEPARTMENT !='IT';


-- 03 MULTIPLE COLUMN SUBQUERY

-- FIND HIGHEST PAID EMPLOYEE IN EACH DEPARTMENT
SELECT 
	EMP_NAME,
    DEPARTMENT,
    SALARY
FROM EMPLOYEES WHERE
(DEPARTMENT,SALARY) IN
	(SELECT 
		DEPARTMENT,
		MAX(SALARY)
	FROM EMPLOYEES 
	GROUP BY DEPARTMENT);


-- 04 CORRELATED SUBQUERY

-- FIND EMPLOYEES EARNING MORE THAN DEPARTMENT AVG SALARY
SELECT 
	E1.EMP_NAME,
    E1.SALARY
FROM EMPLOYEES E1
WHERE SALARY >
	(SELECT
		AVG(SALARY)
	FROM EMPLOYEES E2 
    WHERE E1.DEPARTMENT = E2.DEPARTMENT);


-- 05 SUBQUERY WITH SELECT
-- SHOW EMPLOYEES WITH DEPARTMENT AVG SALARY
SELECT 
	EMP_NAME,
    DEPARTMENT,
    (SELECT AVG(SALARY) FROM EMPLOYEES E2
    WHERE E1.DEPARTMENT = E2.DEPARTMENT) AVG_SALARY_DEPT
FROM EMPLOYEES E1;


-- 06 SUBQUERY WITH FROM 
-- FETCH THE DEPARTMENT AVG SALARY , THAT MUST BE GREATER THAN 60000
SELECT
	DEPARTMENT,
    AVG_SALARY
FROM
	(SELECT
		DEPARTMENT,
		AVG(SALARY) AVG_SALARY
	FROM EMPLOYEES 
	GROUP BY DEPARTMENT) T
WHERE AVG_SALARY>60000;


-- 07.1 SUBQUERY WITH EXISTS
-- FIND EMPLOYEES WHO ARE MANAGERS
SELECT
	EMP_NAME
FROM EMPLOYEES E1
WHERE EXISTS
	(SELECT
		E2.EMP_ID
	FROM EMPLOYEES E2
	WHERE E1.EMP_ID = E2.MANAGER_ID);
   
   
-- 07.2 SUBQUERY WITH NOT EXISTS
-- EMPLOYEES WHO ARE NOT MANAGERS
SELECT
	EMP_NAME
FROM EMPLOYEES E1
WHERE NOT EXISTS
	(SELECT
		E2.EMP_ID
	FROM EMPLOYEES E2
	WHERE E1.EMP_ID = E2.MANAGER_ID);
    







